### ISSUE TITLE
RFC : restructure API

### ISSUE THREAD

**Issue by ludeeus** [ludeeus/googledevices#35]
**Describe the bug**
the api section needs to be restructured.

I'm thinking a split like this make sense:

- googledevices
  - api
    - cast (cast and assistant enabled devices)
      - bluetooth
      - alarms
      - ...
    - wifi (google wifi)
      - info
      - devices
      - ...

**Comment by ludeeus** [comment]
@eliseomartelli any opinions to this?

**Comment by eliseomartelli** [comment]
It looks fine but I think some core elements should be shared at the top level of api

**Comment by ludeeus** [comment]
That would be possible, anything specific you had in mind?

**Comment by eliseomartelli** [comment]
Device Info and common getters/setters should be on the main "scope". 
Platform specific components are better isolated inside a "platform scope".

**Comment by ludeeus** [comment]
device info (and the method for getting that) will be platform specific?
for now, there are two "platforms" none of them have common methods?

Or are you thinking that we add the method to fetch / set in "common space"
like
googledevices.api.info.py
```python
async def get_device_info(self, platform):
    if platform == 'cast':
        # get stuff from cast platform
    elif platform == 'wifi':
       # get stuff from wifi platform
    else:
        print('platform not supported')
```

googledevices.api.cast.info.py
```python
async def get_device_info(self):
    # run platform spesific code here, and return it to parrent method
```

**Comment by eliseomartelli** [comment]
The first option looks fine to me. Is it possible to avoid passing the platform type?

**Comment by ludeeus** [comment]
It was not two different approaches, but one :)
I'm working on a variant of this in #36 will probably be able to finish that later today

**Comment by eliseomartelli** [comment]
Oh, my bad :)
